"""inital migration

Revision ID: 10fc4cb0a96f
Revises: 
Create Date: 2025-09-15 08:57:39.674475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fc4cb0a96f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('deal_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_my_thing', sa.Integer(), nullable=False),
    sa.Column('id_thing_exchange', sa.Integer(), nullable=False),
    sa.Column('answer_user', sa.Boolean(), nullable=True),
    sa.Column('begin_exchange', sa.DateTime(), nullable=True),
    sa.Column('end_exchange', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_my_thing'], ['thing_table.id'], ),
    sa.ForeignKeyConstraint(['id_thing_exchange'], ['thing_table.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_table')
    op.drop_table('thing_table')
    op.drop_table('user_table')
    op.drop_table('admin_table')
    # ### end Alembic commands ###
